### ISSUE TITLE
Wifi Barcode refreshing list again and again and again....

### ISSUE THREAD

**Issue by tiga05** [felixb/WifiBarcode#3]
Hello,

I already wrote you an E-Mail about my problem. I had some time and made my own debugging with the issue and found a solution.
I am not an Android developer, so I am not sure if I am creating any unwanted side effects.

https://github.com/felixb/WifiBarcode/blob/b74d9d7fbfcef7caa25a0fcfa63da8a8182c7236/app/src/main/java/de/ub0r/android/wifibarcode/WifiBarcodeActivity.java#L434-L438

For some reason, the overridden method onResume() is called ALL the time again and again. Maybe its part of the lifecycle(?).

So I just replaced this lines with the lifecycle state "onStart()". Now its only refreshing after start, reopening the app from the background and after returning from the barcode view.

```
    @Override
    protected  void onStart(){
        super.onStart();
        loadWifiConfigurations();
    }
```

**Comment by felixb** [comment]
This might be, because requesting root launches the magisk app, which steals focus from WifiBarcode.
When closing the magisk app, the focus is switched back to the app and `onResume()` is called.

**Comment by felixb** [comment]
I can't publish an update to Google Play w/o major rebuild of that application. The policy requires an target API of 26 (with runtime permissions, ...). Current Android (10) has this feature built in anyway.

**Comment by tiga05** [comment]
That's a pity, but understandable.

If you are sure you wont fix it, close this issue. I fixed the problem for myself, so I'm basically happy 😃.

 Thanks for putting the code on github so I could help myself.
